In [1]:
import pickle
loaded_sc = pickle.load(open("x_scaler.pkl", "rb"))
loaded_scy = pickle.load(open("y_scaler.pkl", "rb"))

preinput = loaded_sc.transform([[1300,12000,4000,0,1]])
preinput

C:\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.46754484, -4.33834816, -1.50743981, -0.5       ,  1.30088727]])

In [3]:
loaded_model = pickle.load(open("svmstartupIOP.sav", "rb"))
result =  loaded_model.predict(preinput)
result

array([-1.03086497])

In [9]:
result = loaded_scy.inverse_transform(result.reshape(-1,1))
result

array([[2.83398213e+09]])